In [2]:
import os
import pandas as pd
import numpy as np
from pathlib import Path
import glob

In [3]:
search_folder = os.path.dirname(os.getcwd()) + "\\원본데이터"
print(search_folder)
file_list = glob.glob(pathname="*.xlsx", root_dir=os.path.abspath(search_folder))
file_list

c:\Users\LeeSeungYong\myproject\[공모전] (신한카드상) 2023년 문화관광 데이터분석대회\tourism\원본데이터

['1-1. 2022 외래관광객조사_Data.xlsx']

### LCA 분석을 위한 전처리

In [4]:
tour = pd.read_excel(os.path.join(search_folder, file_list[0]))

In [5]:
stay = tour.loc[:,'서울일TOT':'제주일TOT']
tour["체류1순위"] = tour.loc[:,'서울일TOT':'제주일TOT'].idxmax(axis = 1)

In [6]:
filt1 = (tour['D_NAT'] == 1) | (tour['D_NAT'] == 2) | (tour['D_NAT'] == 3) | (tour['D_NAT'] == 5) | (tour['D_NAT'] == 9) | (tour['D_NAT'] == 20)
filt2 = (tour['D_NAT'] == 4) | (tour['D_NAT'] == 6) | (tour['D_NAT'] == 7) |(tour['D_NAT'] == 17) |(tour['D_NAT'] == 18) | (tour['D_NAT'] == 19)
filt3 = (tour['D_NAT'] == 8) | (tour['D_NAT'] == 15) | (tour['D_NAT'] == 16)
filt4 = (tour['D_NAT'] == 9) | (tour['D_NAT'] == 10)
filt5 = (tour['D_NAT'] == 11) | (tour['D_NAT'] == 12) | (tour['D_NAT'] == 13) | (tour['D_NAT'] == 14)
filt6 = (tour['D_NAT'] == 97)

In [7]:
tour.loc[filt1, 'D_NAT_CLUST'] = '동아시아'
tour.loc[filt2, 'D_NAT_CLUST'] = '동남아시아'
tour.loc[filt3, 'D_NAT_CLUST'] = '오세아니아,중동'
tour.loc[filt4, 'D_NAT_CLUST'] = '북아메리카'
tour.loc[filt5, 'D_NAT_CLUST'] = '유럽'
tour.loc[filt6, 'D_NAT_CLUST'] = '기타'

In [8]:
# sat = tour.loc[:,'Q4B1':'Q4B3']
tour["만족한활동"] = tour['Q4B1']

In [9]:
selected_columns = tour.loc[:, '서울일TOT':'제주일TOT']
tour['체류2순위'] = selected_columns.apply(lambda x: x.nlargest(2).index[-1] if not np.isnan(x.nlargest(2).iloc[-1]) else '없음', axis=1)

In [10]:
tour

,id,Q1,RQ1,Q3,Q3B1,Q3B2,Q3B3,Q4,Q4A01,Q4A02,...,D_SEX,D_AGE,D_MOK,D_PLA,D_Q1,D_TYP,체류1순위,D_NAT_CLUST,만족한활동,체류2순위
0,276,1,1,4,NaN,NaN,NaN,1,1.0,2.0,...,2,2,4,2,1,1.0,광주일TOT,유럽,3,서울일TOT
1,283,1,1,4,NaN,NaN,NaN,1,1.0,2.0,...,2,2,4,2,1,1.0,경남일TOT,유럽,4,서울일TOT
2,286,1,1,4,NaN,NaN,NaN,1,1.0,2.0,...,1,2,4,2,1,NaN,서울일TOT,유럽,1,부산일TOT
3,289,4,4,2,13.0,NaN,NaN,1,1.0,2.0,...,1,2,2,2,4,1.0,서울일TOT,유럽,4,없음
4,300,1,1,4,NaN,NaN,NaN,1,1.0,2.0,...,2,2,4,3,1,1.0,부산일TOT,동아시아,1,없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19538,41152,3,3,1,1.0,3.0,4.0,1,1.0,2.0,...,1,6,1,3,3,1.0,부산일TOT,동아시아,3,없음
19539,41156,6,4,1,1.0,3.0,2.0,1,1.0,2.0,...,2,6,1,3,4,1.0,부산일TOT,동아시아,2,없음
19540,41157,1,1,2,1.0,3.0,2.0,1,1.0,2.0,...,2,2,2,3,1,1.0,부산일TOT,동남아시아,6,없음
19541,41159,30,4,3,NaN,NaN,NaN,1,NaN,2.0,...,1,3,3,3,4,1.0,부산일TOT,유럽,14,없음
19542,41161,1,1,1,1.0,3.0,4.0,1,1.0,2.0,...,1,3,1,3,1,1.0,서울일TOT,유럽,4,부산일TOT

In [11]:
print(tour.columns)

Index(['id', 'Q1', 'RQ1', 'Q3', 'Q3B1', 'Q3B2', 'Q3B3', 'Q4', 'Q4A01', 'Q4A02',
       ...
       'D_SEX', 'D_AGE', 'D_MOK', 'D_PLA', 'D_Q1', 'D_TYP', '체류1순위',
       'D_NAT_CLUST', '만족한활동', '체류2순위'],
      dtype='object', length=192)

In [12]:
column_name = ['RQ1', 'Q3', 'Q4', 'RQ2A2', 'C총액1인MIS', 'RDAY평균', 'Q7', 'D_BUN', 'D_SEX', 'D_AGE', '체류1순위', '체류2순위',
               'D_NAT_CLUST', '만족한활동'] ## category변수

In [13]:
tour1 = tour[column_name]

In [14]:
tour1.isna().sum()

RQ1               0
Q3                0
Q4                0
RQ2A2             0
C총액1인MIS          0
RDAY평균         4107
Q7                0
D_BUN             0
D_SEX             0
D_AGE             0
체류1순위             0
체류2순위             0
D_NAT_CLUST       0
만족한활동             0
dtype: int64

In [15]:
tour1 = tour1[tour.Q2a1 <= 60]

In [16]:
tour1.isna().sum()

RQ1              0
Q3               0
Q4               0
RQ2A2            0
C총액1인MIS         0
RDAY평균         532
Q7               0
D_BUN            0
D_SEX            0
D_AGE            0
체류1순위            0
체류2순위            0
D_NAT_CLUST      0
만족한활동            0
dtype: int64

In [17]:
tour1 = tour1.dropna()

In [18]:
tour1.to_csv("data/tour_전처리_0720.csv", index = False, encoding = 'utf-8')

In [19]:
cat_name = ['RQ1', 'Q3', 'Q4', 'RQ2A2', 'C총액1인MIS', 'RDAY평균', 'Q7', 'D_BUN', 'D_SEX', 'D_AGE', '체류1순위', '체류2순위',
               'D_NAT_CLUST', '만족한활동', 'D_MON'] ## category변수 + 수치형변수
print(cat_name)

['RQ1', 'Q3', 'Q4', 'RQ2A2', 'C총액1인MIS', 'RDAY평균', 'Q7', 'D_BUN', 'D_SEX', 'D_AGE', '체류1순위', '체류2순위', 'D_NAT_CLUST', '만족한활동', 'D_MON']

In [20]:
drop_col = ['id', '서울박60', '경기박60', '인천박60', 
            '강원박60', '대전박60', '충북박60',
            '충남박60', '세종박60', '경북박60',
            '경남박60', '대구박60', '울산박60',
            '부산박60', '광주박60', '전북박60', 
            '전남박60', '제주박60', '서울일61', 
            '경기일61', '인천일61', '강원일61', 
            '대전일61', '충북일61', '충남일61', 
            '세종일61', '경북일61', '경남일61', 
            '대구일61', '울산일61', '부산일61',
            '광주일61', '전북일61', '전남일61', 
            '제주일61','MQ2A2_61', '호텔숙박60',
            '모텔숙박60', '펜션숙박60', '콘도숙박60',
            '유스숙박60', '야영숙박60', '연수숙박60',
            '한옥숙박60', '게스숙박60', '민박숙박60',
            '휴양숙박60', '친지숙박60', '기타숙박60',  
            'D_NAT', 'D_MOK', 'D_PLA', 'D_Q1', 'D_TYP', 
            '총액1인MIS', 'DAY평균']

num_name = [col for col in tour.columns if col not in cat_name and col not in drop_col]
print(num_name)

['Q1', 'Q3B1', 'Q3B2', 'Q3B3', 'Q4A01', 'Q4A02', 'Q4A03', 'Q4A04', 'Q4A05', 'Q4A06', 'Q4A07', 'Q4A08', 'Q4A09', 'Q4A10', 'Q4A11', 'Q4A12', 'Q4A13', 'Q4A14', 'Q4A15', 'Q4A16', 'Q4A17', 'Q4B1', 'Q4B2', 'Q4B3', 'Q5A01', 'Q5A02', 'Q5A03', 'Q5A04', 'Q5A05', 'Q5A06', 'Q5A07', 'Q5A08', 'Q5A09', 'Q5A10', 'Q5A11', 'Q5A12', 'Q5A13', 'Q5A14', 'Q5A15', 'Q5A16', 'Q5A17', 'KWON1', 'KWON2', 'KWON3', 'KWON4', 'KWON5', 'KWON6', 'KWON7', 'KWON8', '서울박TOT', '경기박TOT', '인천박TOT', '강원박TOT', '대전박TOT', '충북박TOT', '충남박TOT', '세종박TOT', '경북박TOT', '경남박TOT', '대구박TOT', '울산박TOT', '부산박TOT', '광주박TOT', '전북박TOT', '전남박TOT', '제주박TOT', '서울일TOT', '경기일TOT', '인천일TOT', '강원일TOT', '대전일TOT', '충북일TOT', '충남일TOT', '세종일TOT', '경북일TOT', '경남일TOT', '대구일TOT', '울산일TOT', '부산일TOT', '광주일TOT', '전북일TOT', '전남일TOT', '제주일TOT', 'Q2a1', 'Q2a2', 'Q11A$01', 'Q11A$02', 'Q11A$03', 'Q11A$04', 'Q11A$05', 'Q11A$06', 'Q11A$07', 'Q11A$08', 'Q11A$09', 'Q11A$10', 'Q11A$11', 'Q11A$12', 'Q11A$13', 'Q11A$14', 'Q11A$98', 'Q11_1a01t', 'Q11_1a02t', 'Q11_1a03t', 'Q11_1a04t', 'Q11_1a05t', 'Q11_1a06t', 'Q11_1a07t', 'Q11_1a08t', 'Q11_1a09t', 'Q11_1a10t', 'Q11_1a11t', 'Q11_1a12t', 'Q11_1a13t', 'Q11_1a14t', 'Q11_1a15t', 'Q11_1a16t', 'Q11_1a17t', '총액1인TOT', 'DAYall평균', 'Q8', 'Q9']

### LCA 클래스 5개

In [22]:
root_dir = os.path.dirname(os.getcwd())
lca = pd.read_csv(root_dir + "\\LCA결과\\lca_output_5class.csv")

pd.set_option('display.max_row', 500)
pd.set_option('display.max_columns', 100)
lca.style.background_gradient()

In [23]:
rows = ['방한횟수_1회', '방한횟수_2회', '방한횟수_3회', '방한횟수_4회이상', '주요방한목적_여가위락',
        '주요방한목적_친구친지방문', '주요방한목적_사업', '주요방한목적_교육', '주요방한목적_종교및순례',
        '주요방한목적_기타', '여행형태_개별여행', '여행형태_AIRTEL', '여행형태_단체', '체류기간_1-3일', 
        '체류기간_4-7일', '체류기간_8-10일', '체류기간_11-30일', '체류기간_30-60일', '1인경비_$1000이하', 
        '1인경비_$1000~2000', '1인경비_$2000~3000', '1인경비_$3000~5000', '1인경비_$5000~10000', '1day경비_$50이하',
        '1day경비_$50~100', '1day경비_$100~300', '1day경비_$300~500', '1day경비_$500초과', 
        '한국여행에 대한 전반적 만족도_매우 불만족', '한국여행에 대한 전반적 만족도_대체로 불만족', 
        '한국여행에 대한 전반적 만족도_보통', '한국여행에 대한 전반적 만족도_대체로 만족', 
        '한국여행에 대한 전반적 만족도_매우 만족', '향후 3년 내 관광목적 재방문 의향_매우 불만족', 
        '향후 3년 내 관광목적 재방문 의향_대체로 불만족', '향후 3년 내 관광목적 재방문 의향_보통', 
        '향후 3년 내 관광목적 재방문 의향_대체로 만족', '향후 3년 내 관광목적 재방문 의향_매우 만족', 
        '타인 추천 의향_매우 불만족', '타인 추천 의향_대체로 불만족', '타인 추천 의향_보통', '타인 추천 의향_대체로 만족',
        '타인 추천 의향_매우 만족', '분기별_1분기', '분기별_2분기', '분기별_3분기', '분기별_4분기', '성별_남성', '성별_여성',
        '연령별_15-20세', '연령별_21-30세', '연령별_31-40세', '연령별_41-50세', '연령별_51-60세', '연령별_61세 이상']

In [24]:
lca["Unnamed: 0"] = rows

In [25]:
lca["문항"] = lca['Unnamed: 0'].apply(lambda x : x.split('_')[0])
lca["카테고리"] = lca['Unnamed: 0'].apply(lambda x : x.split('_')[1])

In [26]:
lca = lca.drop("Unnamed: 0", axis = 1)

In [27]:
lca = lca[['문항', '카테고리', 'class 1: ', 'class 2: ', 'class 3: ', 'class 4: ', 'class 5: ']]

In [28]:
lca.style.background_gradient()